# Generated by Django 5.1 on 2024-08-22 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_artwork_artist_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='artist_profile',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='myapp.artistprofile'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
