# Generated by Django 5.1 on 2024-08-22 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_artwork_artist_profile_alter_artwork_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='artist_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='myapp.artistprofile'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.artistprofile'),
        ),
    ]
