# Generated by Django 5.1 on 2024-08-24 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_artwork_artist_profile_alter_artwork_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
